// javascript/exercises/__solutions__/ng-shop-state-graphql/src/app/containers/productDetail/productDetail.component.ts
import { Component, OnInit } from '@angular/core';
// import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { FormControl, FormGroup, Validators } from '@angular/forms';

// import { Product } from '@app/models/product.model';
// import { ProductService } from '@app/services/productService';

class MyFormGroup extends FormGroup {
  submitted = false;
}

@Component({
  selector: 'productDetail',
  templateUrl: './productDetail.component.html',
})
export class ProductDetailComponent implements OnInit {
  // product = new Product();
  name?: string;
  productForm: MyFormGroup;

  constructor(
    // private productService: ProductService,
    // private activeRoute: ActivatedRoute,
    private location: Location,
  ) {
    this.productForm = new MyFormGroup({
      sku: new FormControl(''),
      title: new FormControl('', [
        Validators.required,
        Validators.minLength(3),
      ]),
      price: new FormControl('', [Validators.required]),
      basePrice: new FormControl(''),
      desc: new FormControl(''),
      stocked: new FormControl(''),
    });
  }

  ngOnInit(): void {
    // this.product =
    //   (this.activeRoute.snapshot.data['product'] as Product) || new Product();
    // if (!this.product.isNew()) {
    //   this.productForm.patchValue(this.product);
    // }
  }

  onSubmit(form: MyFormGroup) {
    form.submitted = true;
    if (!form.valid) {
      return;
    }

    // this.product = Object.assign(this.product, this.productForm.value);
    // this.productService.save(this.product).subscribe(() => {
    //   this.location.back();
    // });
  }

  onCancel() {
    this.location.back();
  }

  onDelete(event: any) {
    event.preventDefault();
    // this.productService.delete(this.product).subscribe(() => {
    //   this.location.back();
    // });
  }

  fieldGroupClass(fieldName: string) {
    const hasError =
      this.productForm.controls[fieldName].invalid &&
      (this.productForm.controls[fieldName].touched ||
        this.productForm.submitted);
    return { 'has-error': hasError };
  }

  showError(fieldName: string, error: any) {
    return (
      this.productForm.controls[fieldName].hasError(error) &&
      (this.productForm.controls[fieldName].touched ||
        this.productForm.submitted)
    );
  }
}

<h1>Product Detail</h1>

<form (ngSubmit)="onSubmit(productForm)" [formGroup]="productForm">
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label for="sku">Sku *</label>
        <input
          type="text"
          class="form-control"
          formControlName="sku"
          id="sku"
        />
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group" [ngClass]="fieldGroupClass('title')">
        <label for="title">Title *</label>
        <input
          type="text"
          class="form-control"
          formControlName="title"
          id="title"
        />
        <div class="help-block" *ngIf="showError('title', 'required')">
          This field is required
        </div>
        <div class="help-block" *ngIf="showError('title', 'minlength')">
          This field must be longer the 3 characters
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group" [ngClass]="fieldGroupClass('price')">
        <label for="title">Price *</label>
        <input
          type="text"
          class="form-control"
          formControlName="price"
          id="price"
        />
        <div class="help-block" *ngIf="showError('price', 'required')">
          This field is required
        </div>
      </div>
    </div>
  </div>

  <div class=" row ">
    <div class="col-md-6">
      <div class="form-group">
        <label for="title">Base Price</label>
        <input
          type="text"
          class="form-control"
          formControlName="basePrice"
          id="basePrice"
        />
      </div>
    </div>
  </div>

  <div class=" row ">
    <div class="col-md-6">
      <div class="form-group">
        <label for="desc">Description</label>
        <textarea
          class="form-control"
          formControlName="desc"
          id="desc"
        ></textarea>
      </div>
    </div>
  </div>

  <div class=" row ">
    <div class="col-md-6">
      <div class="form-group">
        <label>
          <input type="checkbox" formControlName="stocked" id="stocked" />
          Stocked
        </label>
      </div>
    </div>
  </div>

  <button type="button" class="btn btn-default" (click)="onCancel()">
    Cancel
  </button>
  <button type="submit" class="btn btn-success">Save</button>
  <button
    *ngIf="productId"
    class="btn btn-danger pull-right"
    (click)="onDelete($event)"
  >
    Delete
  </button>
</form>

// javascript/exercises/__solutions__/vue-shop-ts/src/views/ProductDetail.vue
<template>
  <div class="home">
      <h3>Detail</h3>
      <form @submit.prevent="onSubmit()">
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="sku">Sku</label>
            <input type="text"
                  class="form-control"
                  v-model="form.sku"
                  id="sku">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div :class="fieldGroupClass('title')">
            <label for="title">Title *</label>
            <input type="text"
                  class="form-control"
                  v-model="$v.form.title.$model"
                  id="title">
            <div class="help-block" v-if="showError('title', 'required')">
              This field is required
            </div>
            <div class="help-block" v-if="showError('title', 'minLength')">
              This field must be longer the 3 characters
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div :class="fieldGroupClass('price')">
            <label for="title">Price *</label>
            <input type="number"
                  class="form-control"
                  v-model.number="$v.form.price.$model"
                  id="price" step="any">
            <div class="help-block"
                v-if="showError('price', 'required')">
              This field is required
            </div>
          </div>
        </div>
      </div>

      <div class=" row ">
        <div class="col-md-6">
          <div class="form-group">
            <label for="title">Base Price</label>
            <input type="number"
                  step="any"
                  class="form-control"
                  v-model.number="form.basePrice"
                  id="basePrice">
          </div>
        </div>
      </div>

      <div class=" row ">
        <div class="col-md-6">
          <div class="form-group">
            <label for="desc">Description</label>
            <textarea class="form-control"
                      v-model="form.desc"
                      id="desc"></textarea>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>
              <input type="checkbox" id="stocked" v-model="form.stocked"> Stocked
              </label>
          </div>
        </div>
      </div>

      <button type="button"
              class="btn btn-default btn-space"
              @click="onCancel()">Cancel</button>
      <button type="submit"
              class="btn btn-success">Save</button>
      <button v-if="!product.isNew()"
              class="btn btn-danger pull-right"
              @click="onDelete($event)">Delete</button>
    </form>
    <pre>{{$v | json}}</pre>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { required, minLength } from 'vuelidate/lib/validators';

import { Product } from '@/shared/models/product';
import productService from '@/shared/services/productService';

@Component({
  components: {},
  validations: {
    form: {
      title: {
        required,
        minLength: minLength(3),
      },
      price: {
        required,
      },
    },
  },
})
export default class ProductDetail extends Vue {
  product: Product = new Product();
  form = {
    sku: '',
    title: '',
    price: null,
    basePrice: null,
    desc: '',
    stocked: false,
  };

  async mounted() {
    if (this.$route.params.id) {
      this.product = await productService.getById(this.$route.params.id);
      Object.assign(this.form, this.product);
    }
  }

  showError(fieldName: string, errorName: string) {
    const field = this.$v.form[fieldName];
    if (!field) return false;

    return field.$error && !field[errorName];
  }

  fieldGroupClass(fieldName: string) {
    const field = this.$v.form[fieldName];
    if (!field) return null;

    return { 'has-error': field.$error, 'form-group': true };
  }

  onCancel() {
    console.log('onCancel');
  }
  onDelete() {
    console.log('onDelete');
  }
  onSubmit() {
    this.$v.form.$touch();
    if (this.$v.$invalid) return;
    Object.assign(this.product, this.$v.form.$model);
    console.log('onSubmit', this.$v.form.$model);
  }
}
</script>

<style>
.btn-space {
  margin-right: 5px;
}
</style>
