// javascript/exercises/__solutions__/vue-ts-shop-state-vuex/src/App.vue
<template>
  <!-- <div id="app">
    <div id="nav">
      <router-link to="/">Home</router-link> |
      <router-link to="/about">About</router-link>
    </div>
    <router-view/>
  </div> -->
  <div id="app" class="container-fluid">
    <h1>Peter's Web Shop</h1>
    <div class="row">
      <div class="col-md-8">
        <products></products>
      </div>
      <div class="col-md-4">
        <basket></basket>
      </div>
    </div>
  </div>
</template>

<script>
import 'bootstrap/dist/css/bootstrap.css';
import Products from '@/components/products.vue';
import Basket from '@/components/basket.vue';

export default {
  name: 'app',
  components: {
    Products,
    Basket,
  },
};
</script>

<style lang="scss">
</style>

// javascript/exercises/__solutions__/react-shop-state-redux/src/App.jsx
import React, { Component } from 'react';

import ProductsContainer from './containers/ProductsContainer';
import BasketContainer from './containers/BasketContainer';

class App extends Component {
  render() {
    return (
      <div id="app" className="container-fluid">
        <h1>Web Shop</h1>
        <div className="row">
          <div className="col-md-8">
            <ProductsContainer />
          </div>
          <div className="col-md-4">
            <BasketContainer />
          </div>
        </div>
      </div>
    );
  }
}

export default App;
