// javascript/exercises/__solutions__/vue-shop-ts/src/App.vue
<template>
  <div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand"
           routerLink="">My Web Shop</a>
      </div>
      <ul class="nav navbar-nav">
        <li routerLinkActive="active"><router-link to="/">Home</router-link></li>
        <li routerLinkActive="active"><router-link to="/admin">Admin</router-link></li>
      </ul>
    </div>
  </nav>
  <router-view/>
</div>
</template>

<style lang="scss">
</style>

// javascript/exercises/__solutions__/ng-shop-part4-ngrx/src/app/app.component.ts
// app.component.ts
import { Component, OnInit } from '@angular/core';

import { ServiceBus } from '@app/serviceBus';
import { ShopFacade } from '@app/shop.facade';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent implements OnInit {
  errorMessage = '';

  constructor(private serviceBus: ServiceBus, private facade: ShopFacade) {}

  public ngOnInit(): void {
    this.serviceBus.listen('ERROR').subscribe((error) => {
      this.errorMessage = error.message;
    });
    this.facade.loadProducts();
  }
}

<div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" routerLink="">My Web Shop</a>
      </div>
      <ul class="nav navbar-nav">
        <li routerLinkActive="active"><a routerLink="home">Home</a></li>
        <li routerLinkActive="active"><a routerLink="overview">Overview</a></li>
      </ul>
    </div>
  </nav>
  <div class="alert alert-warning" *ngIf="errorMessage">
    {{this.errorMessage}}
  </div>
  <div class="row">
    <div class="col-md-9">
      <router-outlet></router-outlet>
    </div>
    <div class="col-md-3">
      <basket></basket>
    </div>
  </div>
