// javascript/exercises/__solutions__/vue-shop-vuex/src/components/basket.vue
<template>
  <div>
    <h2>Basket</h2>
    <span v-if="basket.items.length === 0">No Product in Basket</span>
    <div v-if="basket.items.length > 0">
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="item in basket.items" :key="item.id">
            <td>{{item.title}}</td>
            <td>{{item.price | currency}}</td>
            <td>{{item.quantity}}</td>
            <td>{{item.total | currency}}</td>
          </tr>
        </tbody>
      </table>
        <h4>Total: {{basket.totalPrice | currency}}</h4>
    </div>
  </div>
</template>

<script>
import { eventBus } from '@/main';
import basketService from '@/services/basketService';
import productService from '@/services/productService';
import { Basket } from '@/models/basket';

export default {
  data() {
    return {
      basket: new Basket(),
    };
  },
  mounted() {
    eventBus.$on('addToBasket', event => {
      this.basket.addProduct(event.product, event.quantity);
    });
    basketService
      .get()
      .then(basket => {
        const promises = [];
        this.basket = basket;
        this.basket.items.forEach(item => {
          promises.push(productService.getById(item.id));
        });
        return Promise.all(promises);
      })
      .then(products => {
        products.forEach(product => {
          this.basket.updateProductInfo(product);
        });
      });
  },
};
</script>

<style scoped>
</style>

// javascript/exercises/__solutions__/ng-shop-part5-graphql/src/app/containers/basket/basket.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
// import { Subscription, forkJoin } from 'rxjs';

// import { ProductService } from '@app/services/productService';
// import { BasketService } from '@app/services/basketService';
// import { Product } from '@app/models/product.model';
// import { Basket } from '@app/models/basket.model';
// import { ServiceBus } from '@app/serviceBus';

@Component({
  selector: 'basket',
  templateUrl: './basket.component.html',
})
export class BasketComponent implements OnInit, OnDestroy {
  // basket: Basket = new Basket();
  // sub?: Subscription;

  constructor() {}

  ngOnInit() {
    // subscribe to product changes
    // this.sub = this.serviceBus.listenForAll().subscribe((event: any) => {
    //   if (event.type === 'addProductToBasket') {
    //     this.basket.addProduct(event.data.product, event.data.quantity);
    //   }
    //   if (event.type === 'productUpdated') {
    //     this.basket.updateProductInfo(event.data);
    //   }
    // });
    // // get basket from server
    // this.basketService.getBasket().subscribe((basket) => {
    //   // for each product in basket, get product info
    //   const productSources: any = [];
    //   basket.items.forEach((item) => {
    //     productSources.push(this.productService.getProduct(item.id));
    //   });
    //   // wait for product info
    //   forkJoin<Product>(productSources).subscribe((products) => {
    //     // update all items in the basket
    //     products.forEach((product) => {
    //       basket.updateProductInfo(product);
    //     });
    //     this.basket = basket;
    //   });
    // });
  }

  onClear() {
    // this.basketService.clear().subscribe(() => {
    //   this.basket = new Basket();
    // });
  }

  ngOnDestroy(): void {
    // if (this.sub) {
    //   this.sub.unsubscribe();
    // }
  }
}

<h3>Basket</h3>
<div>
<!-- <span *ngIf="basket.items.length === 0">No Product in Basket</span>
<div *ngIf="basket.items.length > 0">
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let item of basket.items">
        <td>{{item.title}}</td>
        <td>{{item.price | currency:'EUR':'symbol'}}</td>
        <td>{{item.quantity}}</td>
        <td>{{item.total | currency:'EUR':'symbol'}}</td>
      </tr>
    </tbody>
  </table>
  <h4>Total: {{basket.totalPrice | currency:'EUR':'symbol' }}</h4> -->
  <button class="btn btn-danger" (click)="onClear()">Clear</button>
</div>
