// javascript/exercises/__solutions__/ng-shop-state-ngrx/src/app/containers/productDetail/productDetail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { FormControl, FormGroup, Validators } from '@angular/forms';

import { Product } from '@app/models/product.model';
import { ProductService } from '@app/services/productService';

class MyFormGroup extends FormGroup {
  submitted = false;
}

@Component({
  selector: 'productDetail',
  templateUrl: './productDetail.component.html',
})
export class ProductDetailComponent implements OnInit {
  product = new Product();
  name?: string;
  productForm: MyFormGroup;

  constructor(
    private productService: ProductService,
    private activeRoute: ActivatedRoute,
    private location: Location,
  ) {
    this.productForm = new MyFormGroup({
      sku: new FormControl(''),
      title: new FormControl('', [
        Validators.required,
        Validators.minLength(3),
      ]),
      price: new FormControl('', [Validators.required]),
      basePrice: new FormControl(''),
      desc: new FormControl(''),
      stocked: new FormControl(''),
    });
  }

  ngOnInit(): void {
    this.product =
      (this.activeRoute.snapshot.data['product'] as Product) || new Product();

    if (!this.product.isNew()) {
      this.productForm.patchValue(this.product);
    }
  }

  onSubmit(form: MyFormGroup) {
    form.submitted = true;
    if (!form.valid) {
      return;
    }

    this.product.updateBy(this.productForm.value);
    this.productService.save(this.product).subscribe(() => {
      this.location.back();
    });
  }

  onCancel() {
    this.location.back();
  }

  onDelete(event: any) {
    event.preventDefault();
    this.productService.delete(this.product).subscribe(() => {
      this.location.back();
    });
  }

  fieldGroupClass(fieldName: string) {
    const hasError =
      this.productForm.controls[fieldName].invalid &&
      (this.productForm.controls[fieldName].touched ||
        this.productForm.submitted);
    return { 'has-error': hasError };
  }

  showError(fieldName: string, error: any) {
    return (
      this.productForm.controls[fieldName].hasError(error) &&
      (this.productForm.controls[fieldName].touched ||
        this.productForm.submitted)
    );
  }
}

<h1>Product Detail</h1>

<form (ngSubmit)="onSubmit(productForm)" [formGroup]="productForm">
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label for="sku">Sku</label>
        <input
          type="text"
          class="form-control"
          formControlName="sku"
          id="sku"
        />
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group" [ngClass]="fieldGroupClass('title')">
        <label for="title">Title *</label>
        <input
          type="text"
          class="form-control"
          formControlName="title"
          id="title"
        />
        <div class="help-block" *ngIf="showError('title', 'required')">
          This field is required
        </div>
        <div class="help-block" *ngIf="showError('title', 'minlength')">
          This field must be longer the 3 characters
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group" [ngClass]="fieldGroupClass('price')">
        <label for="title">Price *</label>
        <input
          type="text"
          class="form-control"
          formControlName="price"
          id="price"
        />
        <div class="help-block" *ngIf="showError('price', 'required')">
          This field is required
        </div>
      </div>
    </div>
  </div>

  <div class=" row ">
    <div class="col-md-6">
      <div class="form-group">
        <label for="title">Base Price</label>
        <input
          type="text"
          class="form-control"
          formControlName="basePrice"
          id="basePrice"
        />
      </div>
    </div>
  </div>

  <div class=" row ">
    <div class="col-md-6">
      <div class="form-group">
        <label for="desc">Description</label>
        <textarea
          class="form-control"
          formControlName="desc"
          id="desc"
        ></textarea>
      </div>
    </div>
  </div>

  <div class=" row ">
    <div class="col-md-6">
      <div class="form-group">
        <label>
          <input type="checkbox" formControlName="stocked" id="stocked" />
          Stocked
        </label>
      </div>
    </div>
  </div>

  <button type="button" class="btn btn-default" (click)="onCancel()">
    Cancel
  </button>
  <button type="submit" class="btn btn-success">Save</button>
  <button
    *ngIf="!product.isNew()"
    class="btn btn-danger pull-right"
    (click)="onDelete()"
  >
    Delete
  </button>
</form>

// javascript/exercises/__solutions__/vue-shop/src/views/ProductDetail.vue
<template>
  <div>
    <h1>Product Detail</h1>
    <form>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="sku">Sku</label> <input type="text" class="form-control" id="sku" v-model.trim="form.sku" />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div :class="fieldGroupClass('title')">
            <label for="title">Title *</label>
            <input type="text" class="form-control" id="title" v-model.trim="$v.form.title.$model" />
            <div class="help-block" v-if="showError('title', 'required')">This field is required</div>
            <div class="help-block" v-if="showError('title', 'minLength')">
              This field must be longer the 3 characters
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div :class="fieldGroupClass('price')">
            <label for="title">Price *</label>
            <input type="number" class="form-control" id="price" v-model.trim="$v.form.price.$model" />
            <div class="help-block" v-if="showError('price', 'required')">This field is required</div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="title">Base Price</label>
            <input type="text" class="form-control" id="basePrice" v-model.trim="form.basePrice" />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="desc">Description</label>
            <textarea class="form-control" id="desc" v-model.trim="form.desc"></textarea>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label> <input type="checkbox" id="stocked" v-model.trim="form.stocked" /> Stocked </label>
          </div>
        </div>
      </div>
      <div class="btn-toolbar">
        <button type="submit" class="btn btn-success pull-right" @click.prevent="onSubmit">Save</button>
        <button type="button" class="btn btn-default pull-right" @click="onCancel">Cancel</button>
        <button class="btn btn-danger" @click="onDelete();" v-if="id">Delete</button>
      </div>
    </form>
  </div>
</template>

<script>
import { required, minLength } from 'vuelidate/lib/validators';
import productService from '@/services/productService';
import { Product } from '@/models/product';

export default {
  name: 'productDetail',
  components: {},
  data() {
    return {
      form: {
        sku: '',
        title: '',
        price: null,
        basePrice: null,
        desc: '',
        stocked: false,
      },
      product: new Product({}),
      id: null,
    };
  },
  validations: {
    form: {
      title: {
        required,
        minLength: minLength(3),
      },
      price: {
        required,
      },
    },
  },
  async mounted() {
    if (this.$route.params.id) {
      this.id = this.$route.params.id;
      this.product = await productService.getById(this.id);
      Object.assign(this.form, this.product);
    }
  },
  methods: {
    onCancel() {
      this.$router.push('/admin');
    },
    onSubmit() {
      this.$v.form.$touch();
      if (!this.$v.$invalid) {
        const newProduct = new Product(this.$v.form.$model);
        console.log(newProduct);
        Object.assign(this.product, newProduct);
        console.log(this.product);

        productService.save(this.product).then(this.$router.push('/admin'));
      }
    },
    onDelete() {
      productService.delete(this.id).then(this.$router.push('/admin'));
    },
    showError(fieldName, errorName) {
      const field = this.$v.form[fieldName];
      if (!field) return false;
      return field.$error && !field[errorName];
    },
    fieldGroupClass(fieldName) {
      const field = this.$v.form[fieldName];
      if (!field) return null;
      return { 'has-error': field.$error, 'form-group': true };
    },
  },
};
</script>
