// javascript/exercises/__solutions__/ng-shop-part1/src/app/components/product/product.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'product',
  templateUrl: './product.component.html',
})
export class ProductComponent {
  @Input() product: any;
}

<div class="panel panel-default">
  <div class="panel-heading">{{product.title}}</div>
  <div class="panel-body">
    <img [src]="product.image" width="100%">
    <table class="table">
      <tbody>
        <tr>
          <td><strong>Id:</strong></td>
          <td>{{product.id}}</td>
        </tr>
        <tr>
          <td><strong>Sku:</strong></td>
          <td>{{product.sku}}</td>
        </tr>
        <tr>
          <td><strong>Title:</strong></td>
          <td>{{product.title}}</td>
        </tr>
        <tr>
          <td><strong>Price:</strong></td>
          <td>{{product.price | currency:'EUR':true}}</td>
        </tr>
        <tr>
          <td><strong>Base Price:</strong></td>
          <td>{{product.basePrice | currency:'EUR':true}}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// javascript/exercises/__solutions__/react-shop-part1-products/src/components/Product.jsx
import React from 'react';
import PropTypes from 'prop-types';

import { toCurrency, toPercentage } from '../core/intl';

const Product = ({ product }) => {
  const discount = 100 - (product.price / product.basePrice) * 100;
  return (
    <div>
      <div className="panel panel-default">
        <div className="panel-heading">{product.title}</div>
        <div className="panel-body">
          <img src={product.image} width="100%" />
          <table className="table">
            <tbody>
              <tr>
                <td>
                  <strong>Sku:</strong>
                </td>
                <td>{product.sku}</td>
              </tr>
              <tr>
                <td>
                  <strong>Name:</strong>
                </td>
                <td>{product.title}</td>
              </tr>
              <tr>
                <td>
                  <strong>Price:</strong>
                </td>
                <td>
                  {toCurrency(product.price)}{' '}
                  {!!discount && `( -${toPercentage(discount)})`}
                </td>
              </tr>
            </tbody>
          </table>
          {product.stocked && (
            <span style={{ color: 'red' }}>Out of Stock</span>
          )}
        </div>
      </div>
    </div>
  );
};

Product.propTypes = {
  product: PropTypes.shape({
    sku: PropTypes.string,
    title: PropTypes.string,
    price: PropTypes.number,
    image: PropTypes.string,
    basePrice: PropTypes.number,
  }).isRequired,
};

export default Product;
